# Generated by Django 5.1.6 on 2025-03-07 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='expiers_at',
            new_name='expires_at',
        ),
        migrations.RenameField(
            model_name='otp',
            old_name='phone_numebr',
            new_name='phone_number',
        ),
    ]
