# Generated by Django 5.1.6 on 2025-03-07 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_expiers_at_otp_expires_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='expires_at',
            new_name='expiers_at',
        ),
        migrations.RenameField(
            model_name='otp',
            old_name='phone_number',
            new_name='phone_numebr',
        ),
    ]
